name = "nextDESIGN"
license = "MIT"
licenselink = "https://gitlab.com/mmk2410/nextDESIGN/blob/main/LICENSE"
description = "Simple design created for mmk2410.org"
homepage = "https://mmk2410.org/"
tags = []
features = []
min_version = "0.87.0"

[author]
  name = "Marcel Kapfer"
  homepage = "https://mmk2410.org"
